// <auto-generated />
using System;
using CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CAR_DEALERSHIP_MANGEMENT_SYSTEM.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001100436_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.31")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("CategoryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Description = "Comfortable passenger cars",
                            Name = "Sedan"
                        },
                        new
                        {
                            CategoryId = 2,
                            Description = "Sport utility vehicles",
                            Name = "SUV"
                        },
                        new
                        {
                            CategoryId = 3,
                            Description = "Compact practical cars",
                            Name = "Hatchback"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<int>("CustomerProfileId")
                        .HasColumnType("int");

                    b.Property<string>("DriverLicenseNumber")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("CustomerId");

                    b.HasIndex("CustomerProfileId")
                        .IsUnique();

                    b.HasIndex("DriverLicenseNumber")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("customers");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            CustomerProfileId = 1,
                            DriverLicenseNumber = "DL100001",
                            Email = "ahmed.hassan@example.com",
                            FullName = "Ahmed Hassan",
                            Phone = "01010000001"
                        },
                        new
                        {
                            CustomerId = 2,
                            CustomerProfileId = 2,
                            DriverLicenseNumber = "DL100002",
                            Email = "mona.adel@example.com",
                            FullName = "Mona Adel",
                            Phone = "01010000002"
                        },
                        new
                        {
                            CustomerId = 3,
                            CustomerProfileId = 3,
                            DriverLicenseNumber = "DL100003",
                            Email = "omar.khaled@example.com",
                            FullName = "Omar Khaled",
                            Phone = "01010000003"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.CustomerProfile", b =>
                {
                    b.Property<int>("CustomerProfileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerProfileId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("City")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nationality")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CustomerProfileId");

                    b.ToTable("customerProfiles");

                    b.HasData(
                        new
                        {
                            CustomerProfileId = 1,
                            Address = "12 Nile St.",
                            City = "Cairo",
                            DateOfBirth = new DateTime(1992, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Egypt"
                        },
                        new
                        {
                            CustomerProfileId = 2,
                            Address = "25 Tahrir St.",
                            City = "Giza",
                            DateOfBirth = new DateTime(1995, 7, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Egypt"
                        },
                        new
                        {
                            CustomerProfileId = 3,
                            Address = "18 El Nasr St.",
                            City = "Cairo",
                            DateOfBirth = new DateTime(1988, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nationality = "Egypt"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("HireDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            Email = "mostafa.nabil@autodrive.com",
                            FullName = "Mostafa Nabil",
                            HireDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01020000001",
                            Position = "Sales Manager"
                        },
                        new
                        {
                            EmployeeId = 2,
                            Email = "aya.emad@autodrive.com",
                            FullName = "Aya Emad",
                            HireDate = new DateTime(2022, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01020000002",
                            Position = "Sales Consultant"
                        },
                        new
                        {
                            EmployeeId = 3,
                            Email = "hassan.ali@autodrive.com",
                            FullName = "Hassan Ali",
                            HireDate = new DateTime(2023, 2, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Phone = "01020000003",
                            Position = "Sales Consultant"
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Sale", b =>
                {
                    b.Property<int>("SaleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SaleId"));

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("Notes")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("SalePrice")
                        .HasPrecision(12, 2)
                        .HasColumnType("int");

                    b.HasKey("SaleId");

                    b.HasIndex("CustomerId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("sales");

                    b.HasData(
                        new
                        {
                            SaleId = 1,
                            CustomerId = 1,
                            EmployeeId = 1,
                            Notes = "Completed sale.",
                            PaymentMethod = "Bank Transfer",
                            SaleDate = new DateTime(2026, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 1750000
                        },
                        new
                        {
                            SaleId = 2,
                            CustomerId = 2,
                            EmployeeId = 2,
                            Notes = "Completed sale.",
                            PaymentMethod = "Bank Transfer",
                            SaleDate = new DateTime(2026, 8, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 1850000
                        },
                        new
                        {
                            SaleId = 3,
                            CustomerId = 3,
                            EmployeeId = 3,
                            Notes = "Completed sale.",
                            PaymentMethod = "Cash",
                            SaleDate = new DateTime(2026, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SalePrice = 510000
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("FuelType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Mileage")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasPrecision(12, 2)
                        .HasColumnType("decimal(12,2)");

                    b.Property<int>("SalesId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Available");

                    b.Property<string>("Transmission")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("VehicleId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("SalesId")
                        .IsUnique();

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("vehicles");

                    b.HasData(
                        new
                        {
                            VehicleId = 1,
                            CategoryId = 1,
                            Color = "White",
                            FuelType = "Petrol",
                            Make = "Toyota",
                            Mileage = 12000,
                            Model = "Corolla",
                            Price = 650000m,
                            SalesId = 1,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "VIN00000000000001",
                            Year = 2024
                        },
                        new
                        {
                            VehicleId = 2,
                            CategoryId = 2,
                            Color = "Black",
                            FuelType = "Petrol",
                            Make = "Hyundai",
                            Mileage = 18000,
                            Model = "Elantra",
                            Price = 590000m,
                            SalesId = 2,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "VIN00000000000002",
                            Year = 2023
                        },
                        new
                        {
                            VehicleId = 3,
                            CategoryId = 3,
                            Color = "Grey",
                            FuelType = "Petrol",
                            Make = "KIA",
                            Mileage = 9000,
                            Model = "Sportage",
                            Price = 980000m,
                            SalesId = 3,
                            Status = "Available",
                            Transmission = "Automatic",
                            VIN = "VIN00000000000003",
                            Year = 2024
                        });
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Customer", b =>
                {
                    b.HasOne("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.CustomerProfile", "customerProfile")
                        .WithOne("customer")
                        .HasForeignKey("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Customer", "CustomerProfileId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("customerProfile");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Sale", b =>
                {
                    b.HasOne("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Customer", "customer")
                        .WithMany("Sales")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Employee", "employee")
                        .WithMany("sales")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("customer");

                    b.Navigation("employee");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Vehicle", b =>
                {
                    b.HasOne("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Category", "category")
                        .WithMany("Vehicles")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Sale", "sale")
                        .WithOne("vehicle")
                        .HasForeignKey("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Vehicle", "SalesId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("category");

                    b.Navigation("sale");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Category", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Customer", b =>
                {
                    b.Navigation("Sales");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.CustomerProfile", b =>
                {
                    b.Navigation("customer")
                        .IsRequired();
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Employee", b =>
                {
                    b.Navigation("sales");
                });

            modelBuilder.Entity("CAR_DEALERSHIP_MANGEMENT_SYSTEM.Models.Sale", b =>
                {
                    b.Navigation("vehicle")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
